trigger:
- master
variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'php-service'
  
  # Web app name
  webAppName: 'demo-php-sonata'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Environment name
  environmentName: 'PHP-DEMO'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)
stages:
- stage: DownloadBUild 
  displayName: Download Build file
  variables:
    phpVersion: '7.2'
  jobs:
  - job: DownloadBuild
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UniversalPackages@0
      inputs:
        command: 'download'
        downloadDirectory: '$(System.DefaultWorkingDirectory)'
        feedsToUse: 'internal'
        vstsFeed: 'ad40d9c1-509c-43a0-ac77-e9f953e74080/026ccefc-7dd1-4641-a250-391eb59a33f7'
        vstsFeedPackage: 'a4827469-054e-44b8-8011-e94f17137305'
        vstsPackageVersion: '0.0.1'
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: DownloadBUild
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : demo-php-sonata'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              package: $(System.DefaultWorkingDirectory)